#!/usr/bin/env python3
"""Select and deterministically screen redesigned S2-03T checkpoints.

This process never imports Isaac Lab.  It validates the current campaign's
training manifest, selects at most six checkpoints for safety/contact coverage,
and launches one camera-free evaluator process at a time.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import subprocess
import sys
import time
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from g1_access_push.stage2.s2_03t_redesign_contract import (
    validate_campaign_execution_manifest,
)

EXPECTED_SEEDS = (42, 43, 44)
MAXIMUM_CHECKPOINTS = 6
EXPECTED_ACTOR_INPUT_DIM = 135
EXPECTED_CRITIC_INPUT_DIM = 175
EXPECTED_ACTOR_OUTPUT_DIM = 2
REQUIRED_EXECUTION_SOURCES = (
    "scripts/stage2_isaac/screen_s2_03t_redesign_checkpoints.py",
    "scripts/stage2_isaac/evaluate_s2_03t_checkpoint.py",
    "src/g1_access_push/sim/stage2/s2_03t_actions.py",
    "src/g1_access_push/sim/stage2/s2_03t_env.py",
    "src/g1_access_push/sim/stage2/s2_03t_env_cfg.py",
    "src/g1_access_push/sim/stage2/s2_03t_mdp.py",
    "src/g1_access_push/stage2/s2_03t_redesign_contract.py",
)
PUSH_REASONS = {
    "box_linear_speed",
    "box_angular_speed",
    "box_translation",
    "box_yaw_change",
}
HARD_SAFETY_REASONS = {
    "nonfinite",
    "forbidden_non_palm_box_collision",
    "force_peak",
    "palm_impulse",
    "combined_impulse",
    "force_rate",
    "base_excursion",
    "root_height",
    "root_tilt",
    "arm_joint_margin",
    "arm_torque",
}


def utc_timestamp() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def atomic_write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp.{os.getpid()}")
    with temporary.open("w", encoding="utf-8") as stream:
        json.dump(payload, stream, indent=2, sort_keys=True, allow_nan=False)
        stream.write("\n")
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temporary, path)


def read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"JSON_OBJECT_REQUIRED:{path}")
    return payload


def finite_tree(value: object) -> bool:
    if isinstance(value, float):
        return math.isfinite(value)
    if isinstance(value, Mapping):
        return all(finite_tree(item) for item in value.values())
    if isinstance(value, (list, tuple)):
        return all(finite_tree(item) for item in value)
    return True


def checkpoint_iteration(entry: Mapping[str, Any]) -> int:
    for key in ("iteration", "iteration_field"):
        if key in entry:
            return int(entry[key])
    return int(Path(str(entry["path"])).stem.rsplit("_", 1)[1])


def metric_value(record: Mapping[str, Any], names: Sequence[str], default: float) -> float:
    for name in names:
        value = record.get(name)
        if value is not None:
            try:
                number = float(value)
            except (TypeError, ValueError):
                continue
            if math.isfinite(number):
                return number
    return default


def behavior_record_for_checkpoint(
    curve: Sequence[Mapping[str, Any]], checkpoint_iteration_value: int
) -> Mapping[str, Any]:
    """Return the first rollout generated by the saved post-update policy.

    RSL-RL records rollout ``i`` before PPO update ``i`` and saves ``model_i``
    after that update.  Therefore curve ``i + 1`` is the first direct behavior
    evidence for ``model_i``.  The final checkpoint deliberately has no such
    training-rollout evidence and remains selected by the mandatory FINAL rule.
    """

    expected_iteration = checkpoint_iteration_value + 1
    matches = [item for item in curve if int(item.get("iteration", -1)) == expected_iteration]
    return matches[0] if len(matches) == 1 else {}


def training_score(
    entry: Mapping[str, Any], curve: Sequence[Mapping[str, Any]]
) -> tuple[float, ...]:
    record = behavior_record_for_checkpoint(curve, checkpoint_iteration(entry))
    hard = metric_value(record, ("hard_safety_violation_fraction",), 1.0)
    pushing = metric_value(record, ("pushing_fraction",), 1.0)
    verify = metric_value(record, ("verify_fraction", "bilateral_verify_fraction"), 0.0)
    hold = metric_value(record, ("hold_success_fraction", "success_fraction"), 0.0)
    retention = metric_value(record, ("contact_retention_fraction",), 0.0)
    gap = metric_value(
        record,
        ("minimum_safe_gap_m", "minimum_surface_gap_m", "mean_surface_gap_m"),
        float("inf"),
    )
    force_band = metric_value(
        record, ("force_band_occupancy_fraction", "force_band_occupancy"), 0.0
    )
    return (
        -hard,
        -pushing,
        verify,
        hold,
        retention,
        force_band,
        -gap,
        float(checkpoint_iteration(entry)),
    )


def safe_gap_score(
    entry: Mapping[str, Any], curve: Sequence[Mapping[str, Any]]
) -> tuple[float, ...]:
    """Prefer the smallest gap only inside the frozen pilot safety envelope."""

    record = behavior_record_for_checkpoint(curve, checkpoint_iteration(entry))
    hard = metric_value(record, ("hard_safety_violation_fraction",), 1.0)
    pushing = metric_value(record, ("pushing_fraction",), 1.0)
    gap = metric_value(
        record,
        ("minimum_safe_gap_m", "minimum_surface_gap_m", "mean_surface_gap_m"),
        float("inf"),
    )
    inside_safety_envelope = hard == 0.0 and pushing <= 0.001
    return (float(inside_safety_envelope), -gap, -hard, -pushing)


def validate_checkpoint_policy_contract(entry: Mapping[str, Any]) -> None:
    expected = {
        "actor_input_dim": EXPECTED_ACTOR_INPUT_DIM,
        "critic_input_dim": EXPECTED_CRITIC_INPUT_DIM,
        "actor_output_dim": EXPECTED_ACTOR_OUTPUT_DIM,
    }
    actual = {name: entry.get(name) for name in expected}
    if actual != expected:
        raise ValueError(f"CHECKPOINT_POLICY_CONTRACT_MISMATCH:expected={expected}:actual={actual}")


def select_checkpoints(training_result: Mapping[str, Any], maximum: int) -> list[dict[str, Any]]:
    """Select final and contact/safety specialists without reward-only cherry picking."""

    raw_checkpoints = training_result.get("checkpoints")
    raw_curve = training_result.get("curve")
    if not isinstance(raw_checkpoints, list) or not raw_checkpoints:
        raise ValueError("TRAINING_CHECKPOINTS_MISSING")
    if not isinstance(raw_curve, list) or not raw_curve:
        raise ValueError("TRAINING_CURVE_MISSING")
    checkpoints = [dict(item) for item in raw_checkpoints if isinstance(item, Mapping)]
    curve = [item for item in raw_curve if isinstance(item, Mapping)]
    if not checkpoints or not curve:
        raise ValueError("TRAINING_SELECTION_EVIDENCE_MALFORMED")

    for checkpoint in checkpoints:
        behavior = behavior_record_for_checkpoint(curve, checkpoint_iteration(checkpoint))
        checkpoint["behavior_curve_iteration"] = int(behavior["iteration"]) if behavior else None
        checkpoint["post_update_behavior_metric_missing"] = not bool(behavior)

    criteria = (
        ("FINAL_CHECKPOINT", lambda entry: float(checkpoint_iteration(entry))),
        (
            "BEST_BILATERAL_VERIFY",
            lambda entry: metric_value(
                behavior_record_for_checkpoint(curve, checkpoint_iteration(entry)),
                ("verify_fraction", "bilateral_verify_fraction"),
                0.0,
            ),
        ),
        (
            "BEST_HOLD",
            lambda entry: metric_value(
                behavior_record_for_checkpoint(curve, checkpoint_iteration(entry)),
                ("hold_success_fraction", "success_fraction"),
                0.0,
            ),
        ),
        (
            "BEST_CONTACT_RETENTION",
            lambda entry: metric_value(
                behavior_record_for_checkpoint(curve, checkpoint_iteration(entry)),
                ("contact_retention_fraction",),
                0.0,
            ),
        ),
        (
            "MINIMUM_SAFE_GAP",
            lambda entry: safe_gap_score(entry, curve),
        ),
        ("SAFETY_FIRST_COMPOSITE", lambda entry: training_score(entry, curve)),
    )
    selected: dict[str, dict[str, Any]] = {}
    for reason, key in criteria:
        candidate = max(checkpoints, key=lambda item: (key(item), checkpoint_iteration(item)))
        path = str(Path(str(candidate["path"])).resolve())
        if path not in selected:
            selected[path] = {**candidate, "selection_reasons": [reason]}
        else:
            selected[path]["selection_reasons"].append(reason)
    for candidate in sorted(
        checkpoints, key=lambda item: training_score(item, curve), reverse=True
    ):
        if len(selected) >= maximum:
            break
        path = str(Path(str(candidate["path"])).resolve())
        if path not in selected:
            selected[path] = {**candidate, "selection_reasons": ["SAFETY_FIRST_COMPOSITE_FILL"]}
    return list(selected.values())[:maximum]


def termination_sets(result: Mapping[str, Any]) -> tuple[set[str], set[str]]:
    snapshot = result.get("terminal_snapshot")
    if not isinstance(snapshot, Mapping):
        metadata = result.get("actor_evaluation_metadata")
        snapshot = metadata.get("terminal_snapshot") if isinstance(metadata, Mapping) else None
    reasons = (
        set(snapshot.get("termination_reasons", [])) if isinstance(snapshot, Mapping) else set()
    )
    return reasons & HARD_SAFETY_REASONS, reasons & PUSH_REASONS


def episode_summary(
    result: Mapping[str, Any],
    *,
    seed: int,
    run_root: Path,
    raw_rc: int,
    expected_checkpoint: Path,
    expected_checkpoint_sha256: str,
    expected_checkpoint_iteration: int,
) -> dict[str, Any]:
    snapshot = result.get("terminal_snapshot")
    if not isinstance(snapshot, Mapping):
        snapshot = {}
    hard, pushing = termination_sets(result)
    minimum_gap = snapshot.get("minimum_surface_gap_m", result.get("minimum_surface_gap_m"))
    forces = snapshot.get("maximum_force_n", result.get("maximum_force_n"))
    valid_status = result.get("status") in {"PASS", "FAIL"}
    legacy_packaging = result.get("legacy_packaging_decision_without_camera")
    evidence_contract = bool(
        result.get("authoritative_complete_before_teardown") is True
        and result.get("episode_count") == 1
        and result.get("camera_enabled") is False
        and result.get("camera_free_screening") is True
        and result.get("classifier_image_compatibility_waiver") is True
        and result.get("screening_waiver_scope") == "FINAL_IMAGE_PACKAGING_ONLY"
        and result.get("formal_s2_03_scientific_gates_unchanged") is True
        and isinstance(legacy_packaging, Mapping)
        and legacy_packaging.get("status") == "INVALID"
        and legacy_packaging.get("primary_reason") == "MISSING_FINAL_IMAGE"
        and result.get("terminal_trace_capture") == "PRE_AUTO_RESET_PHYSICS_FRAME"
        and result.get("post_done_steps_executed") == 0
        and int(result.get("reset_count", result.get("post_initial_reset_count", -1))) == 0
        and isinstance(result.get("terminal_snapshot"), Mapping)
        and result.get("action_dim") == EXPECTED_ACTOR_OUTPUT_DIM
        and result.get("actor_observation_dim") == EXPECTED_ACTOR_INPUT_DIM
        and result.get("critic_observation_dim") == EXPECTED_CRITIC_INPUT_DIM
        and result.get("checkpoint") == str(expected_checkpoint)
        and result.get("checkpoint_sha256") == expected_checkpoint_sha256
        and result.get("checkpoint_iteration") == expected_checkpoint_iteration
        and result.get("development_seed") == seed
        and result.get("evaluation_mode") == "SCREENING"
        and result.get("controller_id") == "actor"
    )
    diagnostic_valid = bool(valid_status and evidence_contract and finite_tree(result))
    return {
        "seed": seed,
        "run_root": str(run_root),
        "process_rc": raw_rc,
        "status": result.get("status", "INVALID"),
        "primary_reason": result.get("primary_reason", "EVALUATOR_RESULT_MALFORMED"),
        "diagnostic_valid": diagnostic_valid,
        "contact_occurred": bool(result.get("contact_occurred", False)),
        "bilateral_contact_achieved": bool(result.get("bilateral_contact_achieved", False)),
        "bilateral_verify_completed": bool(snapshot.get("verify_steps", 0) >= 20),
        "safe_hold_completed": bool(snapshot.get("attached_hold_steps", 0) >= 100),
        "contact_retention_steps": int(snapshot.get("contact_retention_steps", 0)),
        "minimum_surface_gap_m": minimum_gap,
        "maximum_force_n": forces,
        "mean_bilateral_force_imbalance_n": result.get("mean_bilateral_force_imbalance_n"),
        "hard_safety_reasons": sorted(hard),
        "pushing_reasons": sorted(pushing),
        "post_initial_reset_count": int(
            result.get("reset_count", result.get("post_initial_reset_count", 0))
        ),
        "forbidden_contact_links": result.get("forbidden_contact_links", []),
        "fall": bool({"base_excursion", "root_height", "root_tilt"} & hard),
        "torque_violation": "arm_torque" in hard,
        "qualified": bool(
            diagnostic_valid
            and result.get("status") == "PASS"
            and result.get("bilateral_contact_achieved") is True
            and snapshot.get("verify_steps", 0) >= 20
            and snapshot.get("attached_hold_steps", 0) >= 100
            and not hard
            and not pushing
            and int(result.get("reset_count", result.get("post_initial_reset_count", 0))) == 0
            and not result.get("forbidden_contact_links", [])
        ),
        "result_json": str(run_root / "result.json"),
    }


def checkpoint_rank(candidate: Mapping[str, Any]) -> tuple[float, ...]:
    episodes = candidate["episodes"]
    hard = sum(bool(item["hard_safety_reasons"]) for item in episodes)
    pushing = sum(bool(item["pushing_reasons"]) for item in episodes)
    verify = sum(bool(item["bilateral_verify_completed"]) for item in episodes)
    hold = sum(bool(item["safe_hold_completed"]) for item in episodes)
    retention = sum(int(item["contact_retention_steps"]) for item in episodes)
    gap_values = [
        0.5 * (float(value[0]) + float(value[1]))
        for item in episodes
        if isinstance((value := item.get("minimum_surface_gap_m")), list) and len(value) == 2
    ]
    force_imbalances = []
    for item in episodes:
        explicit = item.get("mean_bilateral_force_imbalance_n")
        if explicit is not None and math.isfinite(float(explicit)):
            force_imbalances.append(float(explicit))
            continue
        value = item.get("maximum_force_n")
        if isinstance(value, list) and len(value) == 2:
            force_imbalances.append(abs(float(value[0]) - float(value[1])))
    mean_gap = sum(gap_values) / len(gap_values) if gap_values else float("inf")
    mean_force_imbalance = (
        sum(force_imbalances) / len(force_imbalances) if force_imbalances else float("inf")
    )
    return (
        -float(hard),
        -float(pushing),
        float(verify),
        float(hold),
        float(retention),
        -mean_force_imbalance,
        -mean_gap,
        float(candidate["iteration"]),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-root", type=Path, required=True)
    parser.add_argument("--training-root", type=Path, required=True)
    parser.add_argument("--training-source", choices=("PILOT", "FORMAL"), required=True)
    parser.add_argument("--reference", type=Path, required=True)
    parser.add_argument("--reference-sha256", required=True)
    parser.add_argument("--campaign-manifest", type=Path, required=True)
    parser.add_argument("--seeds", type=int, nargs="+", required=True)
    parser.add_argument("--max-checkpoints", type=int, required=True)
    parser.add_argument("--headless", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    run_root = args.run_root.resolve()
    run_root.mkdir(parents=True, exist_ok=False)
    status_path = run_root / "screening_status.json"
    result_path = run_root / "screening_result.json"
    atomic_write_json(status_path, {"status": "STARTING", "timestamp_utc": utc_timestamp()})
    try:
        if tuple(args.seeds) != EXPECTED_SEEDS:
            raise ValueError(f"SCREENING_SEEDS_MISMATCH:{args.seeds}")
        if not 1 <= args.max_checkpoints <= MAXIMUM_CHECKPOINTS:
            raise ValueError(f"MAX_CHECKPOINTS_INVALID:{args.max_checkpoints}")
        if not args.headless:
            raise ValueError("SCREENING_MUST_BE_HEADLESS")
        reference = args.reference.resolve()
        if not reference.is_file() or sha256_file(reference) != args.reference_sha256:
            raise ValueError("PRECONTACT_REFERENCE_SHA_MISMATCH")
        manifest_path = args.campaign_manifest.resolve()
        validate_campaign_execution_manifest(
            manifest_path,
            stage_run_root=run_root,
            reference_path=reference,
            reference_sha256=args.reference_sha256,
            required_source_relatives=REQUIRED_EXECUTION_SOURCES,
        )
        training_root = args.training_root.resolve()
        training = read_json(training_root / "training_result.json")
        if training.get("status") != "PASS" or training.get("mode") != args.training_source:
            raise ValueError("TRAINING_RESULT_NOT_AUTHORITATIVE")
        if not finite_tree(training):
            raise ValueError("TRAINING_RESULT_NONFINITE")
        candidates = select_checkpoints(training, args.max_checkpoints)
        if not candidates:
            raise ValueError("NO_SCREENING_CANDIDATE")

        evaluated: list[dict[str, Any]] = []
        evaluator = Path(__file__).with_name("evaluate_s2_03t_checkpoint.py")
        for candidate in candidates:
            validate_checkpoint_policy_contract(candidate)
            checkpoint = Path(str(candidate["path"])).resolve()
            if checkpoint.name == "model_1999.pt":
                raise ValueError("MODEL_1999_FORBIDDEN")
            if training_root not in checkpoint.parents:
                raise ValueError(f"CHECKPOINT_OUTSIDE_CURRENT_TRAINING_ROOT:{checkpoint}")
            expected_sha = str(candidate.get("sha256", ""))
            if not checkpoint.is_file() or sha256_file(checkpoint) != expected_sha:
                raise ValueError(f"CHECKPOINT_SHA_MISMATCH:{checkpoint}")
            iteration = checkpoint_iteration(candidate)
            episodes = []
            for seed in EXPECTED_SEEDS:
                episode_root = run_root / f"model_{iteration}_seed_{seed}"
                validate_campaign_execution_manifest(
                    manifest_path,
                    stage_run_root=episode_root,
                    reference_path=reference,
                    reference_sha256=args.reference_sha256,
                    required_source_relatives=REQUIRED_EXECUTION_SOURCES,
                )
                command = [
                    sys.executable,
                    str(evaluator),
                    "--run-root",
                    str(episode_root),
                    "--reference",
                    str(reference),
                    "--reference-sha256",
                    args.reference_sha256,
                    "--campaign-manifest",
                    str(manifest_path),
                    "--checkpoint",
                    str(checkpoint),
                    "--checkpoint-sha256",
                    expected_sha,
                    "--checkpoint-iteration",
                    str(iteration),
                    "--controller-id",
                    "actor",
                    "--mode",
                    "screening",
                    "--development-seed",
                    str(seed),
                    "--headless",
                ]
                log_path = run_root / f"model_{iteration}_seed_{seed}.console.log"
                with log_path.open("wb") as log:
                    completed = subprocess.run(
                        command, cwd=Path.cwd(), stdout=log, stderr=subprocess.STDOUT
                    )
                result_file = episode_root / "result.json"
                result = (
                    read_json(result_file)
                    if result_file.is_file()
                    else {
                        "status": "INVALID",
                        "primary_reason": "EVALUATOR_RESULT_MISSING",
                    }
                )
                episodes.append(
                    episode_summary(
                        result,
                        seed=seed,
                        run_root=episode_root,
                        raw_rc=completed.returncode,
                        expected_checkpoint=checkpoint,
                        expected_checkpoint_sha256=expected_sha,
                        expected_checkpoint_iteration=iteration,
                    )
                )
                atomic_write_json(
                    status_path,
                    {
                        "status": "RUNNING",
                        "checkpoint_iteration": iteration,
                        "seed": seed,
                        "completed_episodes": len(evaluated) * len(EXPECTED_SEEDS) + len(episodes),
                        "timestamp_utc": utc_timestamp(),
                    },
                )
            qualified_count = sum(bool(item["qualified"]) for item in episodes)
            evaluated.append(
                {
                    "path": str(checkpoint),
                    "sha256": expected_sha,
                    "size_bytes": checkpoint.stat().st_size,
                    "iteration": iteration,
                    "iteration_field": iteration,
                    "selection_reason": "+".join(candidate["selection_reasons"]),
                    "selection_reasons": candidate["selection_reasons"],
                    "behavior_curve_iteration": candidate["behavior_curve_iteration"],
                    "post_update_behavior_metric_missing": candidate[
                        "post_update_behavior_metric_missing"
                    ],
                    "actor_input_dim": candidate["actor_input_dim"],
                    "critic_input_dim": candidate["critic_input_dim"],
                    "actor_output_dim": candidate["actor_output_dim"],
                    "episodes": episodes,
                    "qualified_seed_count": qualified_count,
                    "qualified": qualified_count == len(EXPECTED_SEEDS),
                }
            )

        all_episodes = [episode for candidate in evaluated for episode in candidate["episodes"]]
        diagnostic_valid = all(bool(item["diagnostic_valid"]) for item in all_episodes)
        qualified = [candidate for candidate in evaluated if candidate["qualified"]]
        best_pool = qualified if qualified else evaluated
        best = max(best_pool, key=checkpoint_rank)
        if not diagnostic_valid:
            status = "INVALID"
            policy_status = "INVALID"
            reason = "SCREENING_EPISODE_INVALID"
        elif qualified:
            status = "PASS"
            policy_status = "PASS"
            reason = "QUALIFIED_CONTACT_POLICY"
        else:
            status = "FAIL"
            policy_status = "FAIL"
            reason = "NO_QUALIFIED_CONTACT_POLICY"
        result = {
            "schema_version": 1,
            "stage": "S2-03T_REDESIGN_CHECKPOINT_SCREENING",
            "status": status,
            "primary_reason": reason,
            "diagnostic_valid": diagnostic_valid,
            "authoritative_complete_before_teardown": True,
            "training_source": args.training_source,
            "training_root": str(training_root),
            "screening_seeds": list(EXPECTED_SEEDS),
            "candidate_count": len(evaluated),
            "screening_episode_count": len(all_episodes),
            "qualified_checkpoint_count": len(qualified),
            "new_policy_status": policy_status,
            "best_checkpoint": {
                key: best[key]
                for key in (
                    "path",
                    "sha256",
                    "size_bytes",
                    "iteration",
                    "iteration_field",
                    "selection_reason",
                    "behavior_curve_iteration",
                    "post_update_behavior_metric_missing",
                    "actor_input_dim",
                    "critic_input_dim",
                    "actor_output_dim",
                    "qualified_seed_count",
                    "qualified",
                )
            },
            "best_checkpoint_sha256": best["sha256"],
            "qualified_seeds": f"{best['qualified_seed_count']}/3",
            "checkpoint_results": evaluated,
            "selection_priority": [
                "no_hard_safety_violation",
                "no_push",
                "bilateral_verify",
                "hold",
                "contact_retention",
                "force_balance",
                "minimum_gap",
                "checkpoint_iteration",
            ],
            "camera_enabled": False,
            "parallel_evaluators": False,
            "box_push_commanded": False,
            "planner_started": False,
            "completed_at_utc": utc_timestamp(),
        }
        atomic_write_json(result_path, result)
        atomic_write_json(
            status_path, {"status": "COMPLETE", "result": status, "timestamp_utc": utc_timestamp()}
        )
        return 0 if status in {"PASS", "FAIL"} else 2
    except BaseException as exc:
        result = {
            "schema_version": 1,
            "stage": "S2-03T_REDESIGN_CHECKPOINT_SCREENING",
            "status": "INVALID",
            "primary_reason": "SCREENING_IMPLEMENTATION_EXCEPTION",
            "diagnostic_valid": False,
            "error": repr(exc),
            "authoritative_complete_before_teardown": True,
            "completed_at_utc": utc_timestamp(),
        }
        atomic_write_json(result_path, result)
        atomic_write_json(
            status_path, {"status": "INVALID", "error": repr(exc), "timestamp_utc": utc_timestamp()}
        )
        raise


if __name__ == "__main__":
    raise SystemExit(main())
